const FOOTER_TEXT =
  "Gracias por su compromiso y dedicación diaria.";
export const FOOTER_PHRASES = [
  "El orden de hoy construye el éxito de mañana.",
  "Un buen equipo comienza con una buena organización.",
  "La disciplina diaria crea grandes resultados.",
  "El compromiso transforma el trabajo en logros.",
  "Cada horario bien hecho es un paso hacia el éxito.",
  "Trabajar con orden es trabajar con calidad.",
  "La constancia convierte el esfuerzo en progreso.",
  "Un equipo organizado trabaja mejor y más tranquilo.",
  "La puntualidad es respeto por todos.",
  "El éxito empieza cuando todos cumplen su parte.",
  "La organización es la base de un buen servicio.",
  "El trabajo en equipo siempre suma.",
  "Cada día bien planificado es un día ganado.",
  "La responsabilidad distingue a los grandes equipos.",
  "Orden, compromiso y resultados.",
  "La excelencia se construye con pequeños hábitos diarios.",
  "Cuando todos colaboran, todo funciona mejor.",
  "Un buen horario mejora el rendimiento del equipo.",
  "La dedicación diaria marca la diferencia.",
  "La organización ahorra tiempo y evita errores.",
  "El esfuerzo constante siempre da frutos.",
  "Un equipo alineado trabaja con armonía.",
  "La planificación es clave para un buen resultado.",
  "El trabajo bien hecho empieza con orden.",
  "La responsabilidad también es puntualidad.",
  "Un día organizado es un día productivo.",
  "La unión del equipo fortalece el resultado.",
  "Cada turno cuenta, cada persona importa.",
  "El compromiso diario construye confianza.",
  "La organización refleja profesionalismo.",
  "El respeto empieza cumpliendo los horarios.",
  "Un buen equipo se apoya y se organiza.",
  "La constancia supera al talento sin disciplina.",
  "La planificación evita improvisaciones.",
  "El orden genera tranquilidad.",
  "La responsabilidad se demuestra con acciones.",
  "Trabajar organizados es trabajar mejor.",
  "El éxito se logra paso a paso.",
  "La puntualidad habla bien de todos.",
  "Un equipo comprometido logra grandes cosas."
];
